# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 16:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_access', models.DateTimeField()),
                ('new_comics', models.BooleanField(default=False)),
                ('new_blogs', models.BooleanField(default=False)),
                ('hide_read', models.BooleanField(default=True)),
                ('alert_new_comics', models.BooleanField(default=True)),
                ('alert_new_blog', models.BooleanField(default=True)),
                ('navigation_max_columns', models.IntegerField(default=5)),
                ('navigation_max_per_column', models.IntegerField(default=20)),
                ('css_color', models.CharField(default='blue_white', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
            options={
                'verbose_name': 'User profile',
                'verbose_name_plural': 'User profiles',
                'ordering': ['user'],
            },
        ),
    ]
