# Generated by Django 4.2.6 on 2023-11-01 23:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_user_userprofile_onetoone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="alert_new_blog",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="alert_new_comics",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="css_color",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="hide_read",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="navigation_max_columns",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="navigation_max_per_column",
        ),
    ]
