# Generated by Django 4.2.11 on 2024-03-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_last_update_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='html',
            field=models.BooleanField(default=False, verbose_name='Is the text HTML?'),
        ),
    ]
