# Generated by Django 4.2.6 on 2023-11-01 23:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_userprofile_remove_unused_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="new_blogs",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="new_comics",
        ),
    ]
