# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 16:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=False, verbose_name='¿Está terminado?')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('notes', models.TextField(verbose_name='Notas')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['state'],
            },
        ),
    ]
