# Generated by Django 4.2.7 on 2023-12-18 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0009_rename_comichistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='custom_func',
            field=models.TextField(blank=True, help_text='Check the <a href="/admin/docs/custom_update/">docs</a> for reference.', null=True, verbose_name='Custom update function'),
        ),
        migrations.AlterField(
            model_name='comic',
            name='referrer',
            field=models.URLField(blank=True, help_text='Set this to a URL that the web will accept as referrer when getting an update.', null=True, verbose_name='Referrer'),
        ),
    ]
