# Generated by Django 4.2.14 on 2024-07-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0013_remove_comic_active_ended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='last_image',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Last image URL'),
        ),
    ]
