# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 16:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('text', models.TextField(verbose_name='Texto')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('html', models.BooleanField(default=False, verbose_name='Si se marca como HTML se pone a pelo en la web, si no, sólo los saltos de línea se convierten.')),
                ('id_topic', models.IntegerField(blank=True, default=0, help_text='Se rellena él sólo', null=True, verbose_name='Id del tema en el foro')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='newblog',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_posts', to='blog.Post'),
        ),
        migrations.AddField(
            model_name='newblog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
