# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-21 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='id_topic',
        ),
        migrations.AlterField(
            model_name='post',
            name='html',
            field=models.BooleanField(default=False, verbose_name='Is the text HTML or plain text?'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
