# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-21 14:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0003_translate_fields_es_to_en'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comic',
            old_name='rating',
            new_name='positive_votes',
        ),
        migrations.RenameField(
            model_name='comic',
            old_name='votes',
            new_name='total_votes',
        ),
    ]
