# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-21 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0005_rename_fields_re'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comic',
            name='fake_user_agent',
        ),
    ]
