# Generated by Django 4.2.6 on 2023-11-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comics", "0007_last_update_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comic",
            old_name="referer",
            new_name="referrer",
        ),
    ]
