# Generated by Django 4.2.7 on 2023-12-19 20:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comics', '0010_alter_comic_custom_func_alter_comic_referrer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UnreadComic',
            new_name='UnreadStrip',
        ),
    ]
