# Generated by Django 4.2.7 on 2023-12-26 10:16

from django.db import migrations, models


def migrate_status(apps, schema_editor):
    Comic = apps.get_model("comics", "Comic")
    db_alias = schema_editor.connection.alias
    all_comics = Comic.objects.using(db_alias).all()
    for comic in all_comics:
        if not comic.active:
            continue
        if comic.ended:
            comic.status = 2
        elif comic.active:
            comic.status = 1
        comic.save()


class Migration(migrations.Migration):
    dependencies = [
        ("comics", "0011_rename_unreadcomic_unreadstrip"),
    ]

    operations = [
        migrations.AddField(
            model_name="comic",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Inactive. Never shown"),
                    (1, "Active"),
                    (2, "Ended"),
                    (3, "Broken"),
                ],
                default=0,
                help_text="An inactive comic is never shown. The rest, depends on the case.",
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="comic",
            name="ended",
            field=models.BooleanField(
                default=False,
                help_text="Check this if the comic has ended.",
                verbose_name="Has ended?",
            ),
        ),

        migrations.RunPython(migrate_status)
    ]
