name: Lint

on:
  pull_request:
    branches:
      - development

env:
  PYTHON_VERSION: 3.12

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      name: Check out source
    - uses: psf/black@stable
      name: Run black
      with:
        # Options: https://github.com/psf/black/blob/stable/docs/usage_and_configuration/the_basics.md
        options: "--force-exclude migrations --check"
        src: "./src"
